TARGET1=quiz4
GCC=gcc

ALL: $(TARGET1) 

$(TARGET1): $(TARGET1).c 
	$(GCC) -o $(TARGET1) $(TARGET1).c 

# $(TARGET1): $(TARGET1).c binary_sems.c error_functions.c get_num.c
# 	$(GCC) -o $(TARGET1) $(TARGET1).c binary_sems.c error_functions.c get_num.c

# $(TARGET2): $(TARGET2).c binary_sems.c error_functions.c get_num.c
# 	$(GCC) -o $(TARGET2) $(TARGET2).c binary_sems.c error_functions.c get_num.c


clean:
	rm -f $(TARGET1) 
